# Generated by Django 2.0.2 on 2018-04-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barners',
            name='for_type',
            field=models.CharField(default='movie', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barners',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Images'),
        ),
        migrations.AlterField(
            model_name='barners',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Movies'),
        ),
        migrations.AlterField(
            model_name='barners',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Series'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Images'),
        ),
    ]
