# Generated by Django 2.0.2 on 2018-04-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180413_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='devices',
            field=models.CharField(choices=[('movie', '720p'), ('episode', '1080p'), ('series', 'ULTRA HD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plans',
            name='movies_limit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('premium', 'Premium')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plans',
            name='quality',
            field=models.CharField(choices=[('mobile', 'Mobile + Internet'), ('tv', 'TV'), ('all', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plans',
            name='shows_limit',
            field=models.IntegerField(),
        ),
    ]
