# Generated by Django 2.0.2 on 2018-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180413_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plans',
            name='duration_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plans',
            name='duration_unit',
            field=models.CharField(choices=[('month', 'Month(s)'), ('yearly', 'Year(s)')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='plans',
            name='devices',
            field=models.CharField(choices=[('mobile', 'Mobile + Internet'), ('tv', 'TV'), ('all', 'All')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plans',
            name='quality',
            field=models.CharField(choices=[('movie', '720p'), ('episode', '1080p'), ('series', 'ULTRA HD')], max_length=10),
        ),
    ]
