# Generated by Django 2.0.2 on 2018-04-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180416_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='movies_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='shows_limit',
            field=models.IntegerField(null=True),
        ),
    ]
