# Generated by Django 2.0.2 on 2018-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180416_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='devices',
            field=models.CharField(choices=[('Mobile + Internet', 'Mobile + Internet'), ('TV', 'TV'), ('ALL', 'All')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plans',
            name='quality',
            field=models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('ULTRA HD', 'ULTRA HD')], max_length=10),
        ),
    ]
