# Generated by Django 2.0.2 on 2018-04-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_genres_moviegenres_seriesgenres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
